### Edit this file as required in order to get the desired att names
###
### In the Apertium expanded lexicons, the first <tag> corresponds to the part of speech. The rest of tags 
### (all enclosed in angle brackets) encode additional morphosyntactic information depending on the pos and 
### lemma. ex:  pizzas:pizza<n><f><pl>
###
### 
### In the resulting LMF lexicon, part of speech is encoded as '<feat att="partOfSpeech" val="tag">'. 
### For other tags:
###
### a) if --tags option is active: 'att' names are read from ApertiumMonolingualTags.pm, thus in the example 
###    above we get: <feat att="gender" val="f"> <feat att="number" val="pl">
### 
### b) if --tags option is NOT active: att names are generated as follows::
###  '<feat att="tag1" val="f">' <feat att="tag2" val="pl">'.
###
### Edit ApertiumMonolingualTags.pm file as required to generate the desired 'att' names.
###
### Here you can find examples for:
### 
### Tags from the EN-ES.ES dictionary
### Tags from the FR-ES.ES dictionary
### Tags from the ES-CA.CA dictionary
### Tags from the ES-CA.ES dictionary
### Tags from the ES-GL.GL dictionary
### Tags from the en-es.en dictionary
### Tags from the fr-es.fr dictionary
### Tags from the it-es.it dictionary
### Tags from the pt-ca.pt dictionary


##Tags from the EN-ES.ES dictionary
##our %Tags=(
##	n => "PartOfSpeech",
##	np =>"PartOfSpeech",
##	adj =>   "PartOfSpeech",
##	adv =>   "PartOfSpeech",
##	preadv =>"PartOfSpeech",
##	pr =>"PartOfSpeech",
##	prn =>   "PartOfSpeech",
##	rel =>   "PartOfSpeech",
##	cnjcoo =>"PartOfSpeech",
##	cnjsub =>"PartOfSpeech",
##	cnjadv =>"PartOfSpeech",
##	vbser => "PartOfSpeech",
##	vbhaver =>   "PartOfSpeech",
##	vblex => "PartOfSpeech",
##	vbmod => "PartOfSpeech",
##	predet =>"PartOfSpeech",
##	det =>   "PartOfSpeech",
##
##	acr =>   "type",
##	loc =>   "type",
##	ant =>   "type",
##	al =>	 "type",
##	cog =>   "type",
##
##	detnt => "type",
##
##	atn =>   "type",
##	enc =>   "type",
##	pro =>   "type",
##	tn =>	"type",
##
##	f => "gender",
##	m => "gender",
##	mf =>	"gender",
##	sg =>	"number",
##	pl =>	"number",
##	   
##	nn =>"type",
##	an =>"type",
##	aa =>"type",
##
##	ind =>   "type",
##	itg =>   "type",
##
##	dem =>   "type",
##	def =>   "type",
##	   
##	nt =>"gender",
##
##	inf =>   "tense",
##	ger =>   "tense",
##	pp =>"tense",
##	pri =>   "tense",
##	p1 =>	"person",
##	p2 =>	"person",
##	p3 =>	"person",
##	pii =>   "tense",
##	ifi =>   "tense",
##	fti =>   "tense",
##	cni =>   "tense",
##	prs =>   "tense",
##	pis =>   "tense",
##	fts =>   "tense",
##	imp =>   "tense",
##
##	pos =>   "type",
##	sp =>    "number",
##	ref =>   "type",
##	sup =>   "type",
##	ord =>   "type",
##	qnt =>   "type",
##	num =>   "PartOfSpeech",
##	pron =>  "type",
##	ij =>	"PartOfSpeech",
##
##	 
##	gen =>   "type",
##	vbdo =>  "PartOfSpeech",
##	comp =>  "type",
##	pres =>  "tense",
##	vaux =>  "PartOfSpeech",
##	ND =>"number",
##	GD =>"gender",
##);

##Tags from the FR-ES.ES dictionary
##our %Tags=(
##	aa => "type",
##	acr => "type",
##	adj => "pos",
##	adv => "type",
##	al => "type",
##	an => "type",
##	ant => "type",
##	atn => "type",
##	cm => "type",
## 	cni => "tense",
##	cnjadv => "pos",
##	cnjcoo => "pos",
##	cnjsub => "pos",
##	ord => "type",
##	def => "type",
##	dem => "type",
##	det => "pos",
##	detnt => "pos",
##	enc => "type",
##	f => "gender",
##	fti => "tense",
##	fts => "tense",
##	ger => "tense",
##	ifi => "tense",
##	ij => "pos",
##	imp => "tense",
##	ind => "type",
##	inf => "tense",
##	itg => "tense",
##	loc => "type",
##	m => "gender",
##	mf => "gender",
##	n => "pos",
##	nn => "type",
##	np => "pos",
##	nt => "gender",
##	num => "pos",
##	p1 => "person",
##	p2 => "person",
##	p3 => "person",
##	pii => "tense",
##	pis => "tense",
##	pl => "number",
##	pos => "type",
##	pp => "tense",
##	pr => "pos",
##	preadv => "pos",
##	predet => "pos",
##	pri => "tense",
##	prn => "pos",
##	pro => "type",
##	prs => "tense",
##	ref => "type",
##	rel => "pos",
##	rpar => "pos",
##	sent => "pos",
##	sg => "number",
##	sp => "number",
##	sup => "type",
##	tn => "type",
##	vbhaver => "pos",
##	vblex => "pos",
##	vbmod => "pos",
##	vbser => "pos",
##	web => "pos",
##	hour => "pos",
##);

##Tags from the ES-CA.CA dictionary
##our %Tags=(
##	detnt => "pos",
##	predet => "pos",
##	atn => "type",
##	enc => "type",
##	pro => "type",
##	tn => "type",
##	acr => "type",
##	loc => "type",
##	ant => "type",
##	al => "type",
##	n => "pos",
##	np => "pos",
##	adj => "pos",
##	f => "gender",
##	m => "gender",
##	mf => "gender",
##	sg => "number",
##	pl => "number",
##	adv => "pos",
##	preadv => "pos",
##	pr => "pos",
##	prn => "pos",
##	rel => "pos",
##	nn => "type",
##	an => "type",
##	aa => "type",
##	ind => "type",
##	itg => "type",
##	det => "pos",
##	dem => "type",
##	def => "type",
##	cnjcoo => "pos",
##	cnjsub => "pos",
##	cnjadv => "pos",
##	nt => "gender",
##	vaux => "pos",
##	vbser => "pos",
##	vbhaver => "pos",
##	vblex => "pos",
##	vbmod => "pos",
##	inf => "tense",
##	ger => "tense",
##	pp => "tense",
##	pri => "tense",
##	ifi => "tense",
##	p1 => "person",
##	p2 => "person",
##	p3 => "person",
##	pii => "tense",
##	fti => "tense",
##	cni => "tense",
##	prs => "tense",
##	pis => "tense",
##	fts => "tense",
##	imp => "tense",
##	pos => "type",
##	gen => "type",
##	nom => "case",
##	sp => "number",
##	ref => "type",
##	sup => "type",
##	num => "pos",
##	ij => "pos",
##	sent => "pos",
##	cm => "pos",
##	lpar => "pos",
##	rpar => "pos",
##	lquest => "pos",
##	web => "pos",
##);

##	Tags from the ES-CA.ES dictionary
##	our %Tags=(
##	acr => "type",
##	v2 => "v2",
##	predet => "pos",
##	detnt => "pos",
##	loc => "type",
##	ant => "type",
##	al => "type",
##	enc => "type",
##	pro => "type",
##	tn => "type",
##	n => "pos",
##	np => "pos",
##	adj => "pos",
##	f => "gender",
##	m => "gender",
##	mf => "gender",
##	sg => "number",
##	pl => "number",
##	adv => "pos",
##	preadv => "pos",
##	pr => "pos",
##	prn => "pos",
##	rel => "pos",
##	nn => "type",
##	an => "type",
##	aa => "type",
##	ind => "type",
##	itg => "type",
##	det => "pos",
##	dem => "type",
##	def => "type",
##	cnjcoo => "pos",
##	cnjsub => "pos",
##	cnjadv => "pos",
##	nt => "gender",
##	vbser => "pos",
##	vbhaver => "pos",
##	vblex => "pos",
##	vbmod => "pos",
##	inf => "tense",
##	ger => "tense",
##	pp => "tense",
##	pri => "tense",
##	p1 => "person",
##	p2 => "person",
##	p3 => "person",
##	pii => "tense",
##	ifi => "tense",
##	fti => "tense",
##	cni => "tense",
##	prs => "tense",
##	pis => "tense",
##	fts => "tense",
##	imp => "tense",
##	pos => "type",
##	sp => "number",
##	ref => "type",
##	sup => "type",
##	num => "pos",
##	ij => "pos",
##	sent => "pos",
##	cm => "pos",
##	lpar => "pos",
##	rpar => "pos",
##	lquest => "pos",
##	web => "pos:1",
##	);

##Tags from the ES-GL.GL dictionary
##our %Tags=(
##	aa => "type",
##	acr => "type",
##	adj => "pos",
##	adv => "pos",
##	al => "type",
##	an => "type",
##	ant => "type",
##	atn => "type",
##	cm => "pos",
##	cni => "tense",
##	cnjadv => "pos",
##	cnjcoo => "pos",
##	cnjsub => "pos",
##	def => "type",
##	dem => "type",
##	det => "pos",
##	detnt => "pos",
##	enc => "type",
##	f => "gender",
##	fti => "tense",
##	fts => "tense",
##	GD => "gender",
##	ger => "tense",
##	gerps => "tense",
##	ifi => "tense",
##	ij => "pos",
##	imp => "tense",
##	ind => "type",
##	inf => "tense",
##	infps => "tense",
##	itg => "type",
##	loc => "type",
##	lpar => "pos",
##	lquest => "pos",
##	m => "gender",
##	mf => "gender",
##	n => "gender",
##	ND => "type",
##	nn => "type",
##	np => "pos",
##	nt => "gender",
##	num => "type",
##	p1 => "person",
##	p2 => "person",
##	p3 => "person",
##	pii => "tense",
##	pis => "tense",
##	pl => "number",
##	pmp => "tense",
##	pos => "type",
##	pp => "tense",
##	pr => "pos",
##	preadv => "pos",
##	predet => "pos",
##	pri => "tense",
##	prn => "type",
##	pro => "type",
##	prs => "tense",
##	ref => "type",
##	rel => "pos",
##	rpar => "pos",
##	sent => "pos",
##	sg => "number",
##	sp => "number",
##	sup => "type",
##	tn => "type",
##	vbhaver => "pos",
##	vblex => "pos",
##	vbmod => "pos",
##	vbser => "pos",
##	web => "pos",
##);
##Tags from the en-es.en dictionary
##our %Tags=(
##	acr => "type",
##	predet => "pos",
##	detnt => "pos",
##	loc => "type",
##	ant => "type",
##	al => "type",
##	cog => "type",
##	atn => "type",
##	enc => "type",
##	pro => "type",
##	tn => "type",
##	n => "pos",
##	np => "pos",
##	adj => "pos",
##	f => "gender",
##	m => "gender",
##	mf => "gender",
##	sg => "number",
##	pl => "number",
##	adv => "pos",
##	preadv => "pos",
##	pr => "pos",
##	prn => "pos",
##	rel => "pos",
##	nn => "type",
##	an => "type",
##	aa => "type",
##	ind => "type",
##	itg => "type",
##	det => "pos",
##	dem => "type",
##	def => "type",
##	cnjcoo => "pos",
##	cnjsub => "pos",
##	cnjadv => "pos",
##	nt => "gender",
##	vbser => "pos",
##	vbhaver => "pos",
##	vblex => "pos",
##	vbmod => "pos",
##	inf => "tense",
##	ger => "tense",
##	pp => "tense",
##	pri => "tense",
##	p1 => "First",
##	p2 => "Second",
##	p3 => "person",
##	pii => "tense",
##	ifi => "tense",
##	fti => "tense",
##	cni => "tense",
##	prs => "tense",
##	pis => "tense",
##	fts => "tense",
##	imp => "tense",
##	pos => "tense",
##	sp => "number",
##	ref => "type",
##	sup => "type",
##	ord => "type",
##	qnt => "type",
##	num => "pos",
##	pron => "type",
##	ij => "pos",
##	sent => "pos",
##	cm => "pos",
##	lpar => "pos",
##	rpar => "pos",
##	lquest => "pos",
##	web => "pos",
##	apos => "pos",
##	percent => "pos",
##	time => "type",
##	    
##	past => "tense",
##	sep => "separable-type",
##	sint => "type",
##
##	obj => "type",
##	subj => "type",
##	subs => "substantive",
##	pprs => "tense",
##
##	gen => "case",
##	vbdo => "pos",
##	comp => "type",
##	pres => "tense",
##	vaux => "pos",
##	ND => "number",
##	GD => "gender",
##);


##Tags from the fr-es.fr dictionary
##our %Tags=(
##	aa  =>  "type",
##	acr  =>  "type",
##	adj  =>  "pos",
##	adv  =>  "pos",
##	al  =>  "type",
##	an  =>  "type",
##	ant  =>  "type",
##	atn  =>  "type",
##
##	cni  =>  "tense",
##	cnjadv  =>  "pos",
##	cnjcoo  =>  "pos",
##	cnjsub  =>  "pos",
##	def  =>  "type",
##	dem  =>  "type",
##	det  =>  "pos",
##	detnt  =>  "pos",
##	enc  =>  "type",
##	f  =>  "gender",
##	fti  =>  "tense",
##	fts  =>  "tense",
##	gen  =>  "tense",
##	ger  =>  "tense",
##	ifi  =>  "tense",
##	ij  =>  "pos",
##	imp  =>  "tense",
##	ind  =>  "type",
##	inf  =>  "tense",
##	itg  =>  "type",
##	loc  =>  "type",
##	    
##	ord  =>  "type",
##	m  =>  "gender",
##	mf  =>  "gender",
##	n  =>  "pos",
##	nn  =>  "type",
##	nom  =>  "case",
##	np  =>  "pos",
##	nt  =>  "gender",
##	num  =>  "pos",
##	p1  =>  "person",
##	p2  =>  "person",
##	p3  =>  "person",
##
##	pii  =>  "tense",
##	pis  =>  "tense",
##	pl  =>  "number",
##	pos  =>  "type",
##	pp  =>  "tense",
##	ppres  =>  "tense",
##	pr  =>  "pos",
##	preadv  =>  "pos",
##	predet  =>  "pos",
##	pri  =>  "tense",
##	prn  =>  "pos",
##	pro  =>  "type",
##	prs  =>  "tense",
##	ref  =>  "type",
##	rel  =>  "pos",
##
##	sg  =>  "number",
##	sp  =>  "number",
##	sup  =>  "type",
##	tn  =>  "type",
##	vaux  =>  "pos",
##	vbhaver  =>  "pos",
##	vblex  =>  "pos",
##	vbmod  =>  "pos",
##	vbser  =>  "pos",
##	ND  =>  "number",
##);

####Tags from the es-it.it dictionary
##our %Tags=(
##	acr  =>  "type", 
##	predet  =>  "pos", 
##	detnt  =>  "pos", 
##	loc  =>  "type", 
##	cog  =>  "type", 
##	ant  =>  "type", 
##	al  =>  "type", 
##	atn  =>  "type", 
##	enc  =>  "type", 
##	auxser  =>  "pos", 
##	pro  =>  "type", 
##	tn  =>  "type", 
##	n  =>  "pos", 
##	np  =>  "pos", 
##	adj  =>  "pos", 
##	f  =>  "gender", 
##	m  =>  "gender", 
##	mf  =>  "gender", 
##	GD  =>  "gender", 
##	sg  =>  "number", 
##	pl  =>  "number", 
##	ND  =>  "number", 
##	adv  =>  "pos", 
##	preadv  =>  "pos", 
##	pr  =>  "pos", 
##	prn  =>  "pos", 
##	rel  =>  "pos", 
##	nn  =>  "type", 
##	an  =>  "type", 
##	aa  =>  "type", 
##	ind  =>  "type", 
##	itg  =>  "type", 
##	det  =>  "pos", 
##	dem  =>  "type", 
##	def  =>  "type", 
##	cnjcoo  =>  "pos", 
##	cnjsub  =>  "pos", 
##	cnjadv  =>  "pos", 
##	nt  =>  "gender", 
##	vbser  =>  "pos", 
##	vbhaver  =>  "pos", 
##	vblex  =>  "pos", 
##	vbmod  =>  "pos", 
##	inf  =>  "tense", 
##	ger  =>  "tense", 
##	pp  =>  "tense", 
##	pri  =>  "tense", 
##	p1  =>  "person", 
##	p2  =>  "person", 
##	p3  =>  "person", 
##	pii  =>  "tense", 
##	ifi  =>  "tense", 
##	fti  =>  "tense", 
##	cni  =>  "tense", 
##	prs  =>  "tense", 
##	pis  =>  "tense", 
##	fts  =>  "tense", 
##	imp  =>  "tense", 
##	pos  =>  "type", 
##	sp  =>  "number", 
##	ref  =>  "type", 
##	sup  =>  "type", 
##	num  =>  "pos", 
##	ij  =>  "pos", 
##);

####Tags from the pt-ca.pt dictionary
our %Tags=(	
	acr  =>  "type", 
	predet  =>  "pos", 
	detnt  =>  "pos", 
	loc  =>  "type", 
	ant  =>  "type", 
	al  =>  "type", 
	atn  =>  "type", 
	enc  =>  "type", 
	pro  =>  "type", 
	tn  =>  "type", 
	n  =>  "pos", 
	np  =>  "pos", 
	adj  =>  "pos", 
	f  =>  "gender", 
	m  =>  "gender", 
	mf  =>  "gender", 
	sg  =>  "number", 
	pl  =>  "number", 
	adv  =>  "pos", 
	preadv  =>  "pos", 
	pr  =>  "pos", 
	prn  =>  "pos", 
	rel  =>  "pos", 
	nn  =>  "type", 
	an  =>  "type", 
	aa  =>  "type", 
	ind  =>  "type", 
	itg  =>  "type", 
	det  =>  "pos", 
	dem  =>  "type", 
	def  =>  "type", 
	cnjcoo  =>  "pos", 
	cnjsub  =>  "pos", 
	cnjadv  =>  "pos", 
	nt  =>  "gender", 
	vbser  =>  "pos", 
	vbhaver  =>  "pos", 
	vblex  =>  "pos", 
	vbmod  =>  "pos", 
	inf  =>  "tense", 
	ger  =>  "tense", 
	pp  =>  "tense", 
	pri  =>  "tense", 
	p1  =>  "person", 
	p2  =>  "person", 
	p3  =>  "person", 
	pii  =>  "tense", 
	ifi  =>  "tense", 
	fti  =>  "tense", 
	cni  =>  "tense", 
	prs  =>  "tense", 
	pis  =>  "tense", 
	fts  =>  "tense", 
	imp  =>  "tense", 
	pos  =>  "type", 
	sp  =>  "number", 
	ref  =>  "type", 
	sup  =>  "type", 
	num  =>  "pos", 
	ij  =>  "pos", 
	   
	pmp  =>  "tense", 
	infps  =>  "tense", 
	cuavb  =>  "pos", 
);  



